-- Mock Submissions for Testing
-- Run this in your database client (Supabase SQL Editor, pgAdmin, etc.)

INSERT INTO submissions (name, email, subject, content, ip_address, status, created_at) VALUES

-- Mental Health Related Submissions
('Sarah Johnson', 'sarah.j@email.com', 'Struggling with anxiety and work pressure', 'Hi there, I love your blog and find your posts really helpful. I''ve been struggling with anxiety lately, especially with work pressure mounting up. It feels like I''m constantly on edge and I can''t seem to switch off even when I get home. Do you have any advice on managing work-related anxiety? I feel like I''m drowning and could really use some guidance on how to cope better. Thank you for all the work you do - your posts have been a lifeline for me.', '192.168.1.100', 'pending', '2024-12-20 10:30:00+00'),

('Marcus Chen', 'marcus.chen.dev@gmail.com', 'Impostor syndrome in tech career', 'Your recent post about self-doubt really resonated with me. I''m a software developer with 3 years of experience, but I constantly feel like I don''t belong and that everyone around me is smarter. Every code review makes me anxious, and I''m terrified of being "found out" as incompetent. How do you deal with impostor syndrome, especially in a competitive field like tech? I''m considering leaving the industry because the stress is overwhelming.', '10.0.0.45', 'pending', '2024-12-19 15:45:00+00'),

('Emma Rodriguez', 'emma.writes@outlook.com', 'Dealing with toxic family relationships', 'I hope you can address toxic family dynamics in a future post. I''ve been struggling with setting boundaries with my parents who are very controlling and emotionally manipulative. They make me feel guilty whenever I try to live my own life or make my own decisions. I''m 28 years old but still feel like a child around them. How do you maintain relationships with family members who are toxic but still important to you? It''s tearing me apart.', '203.45.67.89', 'reviewed', '2024-12-18 09:15:00+00'),

-- Career and Life Transitions
('David Park', 'dpark.finance@yahoo.com', 'Career burnout and finding purpose', 'I''ve been working in finance for 8 years and I''m completely burned out. The money is good but I feel empty and unfulfilled. I dread going to work every morning and I''ve lost all passion for what I do. I want to make a career change but I''m scared of starting over and taking a pay cut. How do you find the courage to completely change your life when you''re comfortable but miserable?', '172.16.0.23', 'pending', '2024-12-17 14:20:00+00'),

('Lisa Thompson', 'lisa.creative@gmail.com', 'Perfectionism is paralyzing me', 'Your writing about perfectionism hit so close to home. I''m a graphic designer and my perfectionism has become paralyzing. I spend hours obsessing over tiny details and I''ve started avoiding new projects because I''m afraid they won''t be perfect. It''s affecting my work, my relationships, and my mental health. I know perfectionism is supposed to be a "good" trait but it''s destroying my life. How do you overcome the need to be perfect all the time?', '198.51.100.42', 'pending', '2024-12-16 11:30:00+00'),

-- Relationships and Personal Growth
('Alex Rivera', 'alex.thoughts@protonmail.com', 'Social anxiety and making friends as an adult', 'Making friends as an adult is so hard, especially with social anxiety. I moved to a new city for work 2 years ago and I still don''t have any close friends. I want to put myself out there but social situations make me incredibly anxious. I overthink every interaction and convince myself that people don''t like me. How do you build genuine friendships when you''re introverted and anxious? I''m so lonely and it''s affecting my mental health.', '203.0.113.15', 'pending', '2024-12-15 16:45:00+00'),

('Taylor Kim', 'taylor.k.wellness@gmail.com', 'Body image and self-acceptance', 'I struggle so much with body image and self-acceptance. Social media makes it worse - I constantly compare myself to others and feel inadequate. I know intellectually that those images are filtered and edited but emotionally it still affects me. I''ve tried dieting, exercise, therapy, but I still hate how I look. How do you learn to love yourself when society tells you you''re not enough? I''m tired of hating my body but I don''t know how to stop.', '192.0.2.100', 'reviewed', '2024-12-14 13:20:00+00'),

-- Life Challenges and Coping
('Jordan Williams', 'jordan.w.student@edu.com', 'Grief and moving forward after loss', 'I lost my mom to cancer 6 months ago and I''m struggling to move forward. Everyone says it gets easier with time but it feels like it''s getting harder. I feel guilty when I have good days, like I''m betraying her memory by being happy. I don''t know how to process this grief while still trying to live my life. Work, friends, everything feels meaningless now. How do you carry grief while still finding joy in life? I feel so lost.', '198.18.0.50', 'pending', '2024-12-13 08:45:00+00'),

('Casey Brown', 'casey.recovery.journey@gmail.com', 'Addiction recovery and rebuilding trust', 'I''ve been sober for 8 months now and while I''m proud of that, rebuilding relationships has been incredibly difficult. My family and friends are supportive but I can see the wariness in their eyes. They''re waiting for me to mess up again. I don''t blame them - I''ve broken their trust many times before. How do you rebuild relationships after addiction? How do you live with the shame and guilt while trying to move forward? Recovery is lonely even when you''re surrounded by people who love you.', '203.0.113.200', 'pending', '2024-12-12 19:30:00+00'),

-- Recent Submissions (more urgent tone)
('Mia Santos', 'mia.urgent.help@gmail.com', 'Please help - panic attacks getting worse', 'I''m sorry to bother you but I''m desperate for help. My panic attacks have been getting worse and I don''t know what to do. They happen randomly and I feel like I''m dying. I''ve been to the ER three times thinking I was having a heart attack. The doctors say it''s anxiety but it feels so real and terrifying. I''m scared to leave my house now because what if I have one in public? Can you please write about panic attacks and how to manage them? I need help and I don''t know where else to turn.', '10.0.1.75', 'pending', '2024-12-23 22:15:00+00'),

('Ryan O''Connor', 'ryan.oconnor.needs.advice@gmail.com', 'Relationship ended and I feel worthless', 'My girlfriend of 3 years just broke up with me and I feel completely worthless. She said she needs space to work on herself but I can''t help feeling like I wasn''t good enough. I keep replaying every conversation, every mistake I made. I can''t eat, I can''t sleep, and I can''t focus on anything. All my friends are tired of hearing about it. How do you cope with heartbreak when it feels like your world has ended? I''ve never felt this low before and I''m scared of these dark thoughts I''m having.', '172.20.10.5', 'pending', '2024-12-23 18:45:00+00');